### ISSUE TITLE
Restructure ansible to be a Galaxy Collection

### ISSUE THREAD

**Issue by tmgstevens** [redpanda-data/deployment-automation#110]
We need to restructure the ansible directory to be formatted as an Ansible Galaxy Collection before submitting to https://galaxy.ansible.com/. 

For details of Ansible Galaxy Collections see https://docs.ansible.com/ansible/latest/collections_guide/index.html

**Comment by gene-redpanda** [comment]
Complete https://galaxy.ansible.com/redpanda/cluster
