### ISSUE TITLE
Establish restart fails in some conditions because package_result isn't populated right

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/deployment-automation#155]
in start-redpanda.yml, the task that establishes if a restart is necessary seems to fail on occasion when the package_result registered variable is checked for the `results` key. Not sure why it's missing in some cases, but this seems to at least be the fix for now. Documenting it for now so we can get a branch made and tested

```diff --git a/ansible/playbooks/roles/redpanda_broker/tasks/start-redpanda.yml b/ansible/playbooks/roles/redpanda_broker/tasks/start-redpanda.yml
index 1ff9680..42a9827 100644
--- a/ansible/playbooks/roles/redpanda_broker/tasks/start-redpanda.yml
+++ b/ansible/playbooks/roles/redpanda_broker/tasks/start-redpanda.yml
@@ -210,7 +210,8 @@
 #
 - name: Establish whether restart required
   ansible.builtin.set_fact:
-    restart_required: '{{ ("true" in restart_required_rc.stdout or (is_initialized and (nodeconfig_result.changed or "Removed" in package_result.results or "1 upgraded" in package_result.results))) and (restart_node | default("true") | bool) }}'
+    restart_required: '{{ ("true" in restart_required_rc.stdout or (is_initialized and (nodeconfig_result.changed or package_result.results is defined and ("Removed" in package_result.results or "1 upgraded" in package_result.results)))) and (restart_node | default("true") | bool) }}'


 # serial: 1 would be the proper solution here, but that can only be set on play level```

[Slack Message](https://redpandadata.slack.com/archives/C049AE7V4U8/p1678491547657399?thread_ts=1678485045.593989&cid=C049AE7V4U8)

**Comment by hcoyote** [comment]
Error message without this workaround:

```FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'results'. 'dict object' has no attribute 'results'\n\nThe error appears to be in '/Users/cnelson/sandbox/deployment-automation/ansible/playbooks/roles/redpanda_broker/tasks/start-redpanda.yml': line 211, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#\n- name: Establish whether restart required\n  ^ here\n"}```

**Comment by gene-redpanda** [comment]
Since we have a solution mind opening a PR for it? This would be very nice to have 😄

**Comment by hcoyote** [comment]
I'll create a PR next week. Can't do it right now.

other details: looking at the ansible debugger during the failed task runs shows:

`          'package_result': {'changed': False,
                             'skip_reason': 'Conditional result was False',
                             'skipped': True},`

**Comment by gene-redpanda** [comment]
Completed a while ago
