### ISSUE TITLE
Set the Redpanda license

### ISSUE THREAD

**Issue by RafalKorepta** [redpanda-data/deployment-automation#160]
Redpanda will eventually enforce license for enterprise feature like tiered storage. It would be good to set it up.
Example:
https://github.com/redpanda-data/helm-charts/blob/1c1048b68950f0dbe454d41448db420b7b115423/charts/redpanda/templates/post-install-upgrade-job.yaml#L107
https://github.com/redpanda-data/redpanda/blob/dev/src/go/rpk/pkg/cli/cmd/cluster/license/set.go

**Comment by gene-redpanda** [comment]
Done
