### ISSUE TITLE
node_exporter only needed by grafana/prometheus, so move to grafana install playbook

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/deployment-automation#164]
We're pulling in geerlingguy.node_exporter in during install-node-deps for Redpanda. This isn't strictly required, as the only thing that needs it is the grafana/prometheus hook. The dependency should probably instead be in `deploy-prometheus-grafana.yml` and not in `install-node-deps.yml`. This will help further decrease the install/dependency surface area for supporting the ansible redpanda_broker role in airgapped setups.

ansible/roles/redpanda_broker/defaults/main.yml
26:node_exporter_version: "{{ node_exporter_custom_version | default('1.5.0') }}"

ansible/roles/redpanda_broker/tasks/install-node-deps.yml
4:    name: geerlingguy.node_exporter

**Comment by gene-redpanda** [comment]
https://github.com/redpanda-data/redpanda-ansible-collection/pull/3
