### ISSUE TITLE
Default Ubuntu version is 20.04 but 23.3.x has retired support for that version

### ISSUE THREAD

**Issue by WesWWagner** [redpanda-data/deployment-automation#212]
Pretty much the issue is in the title of this one. Our official docs state that Ubuntu 21 or later is needed for 23.3.x , and we are installing latest redpanda by default from the settings passed to the redpanda galaxy code.

**Comment by hcoyote** [comment]
@WesWWagner 23.3 still says 20.04 is supported.

https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/requirements/
> Minimum version required of Ubuntu: 20.04 LTS. Recommended: 22.04+



https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/k-requirements/
> Minimum version required of Ubuntu: 20.04 LTS. Recommended: 22.04+

where do you see that Ubuntu 21 is required?

**Comment by hcoyote** [comment]
cc @Feediver1 

Not sure if this is a docs issue or if we actually did remove support for the 22.04 LTS for Ubuntu. I couldn't find an issue in the redpanda repo talking about the removal of support

**Comment by WesWWagner** [comment]
Actually it seems like that change to docs has been reverted... so I guess we are still supporting 20.04

A few weeks ago I saw we had moved it up to 21.x

**Comment by hcoyote** [comment]
Got it. I'll close this out then.
