### ISSUE TITLE
AWS Cloudformation demo

### ISSUE THREAD

**Issue by chadbrewbaker** [redpanda-data/deployment-automation#39]
I was asked to move https://github.com/vectorizedio/redpanda/issues/2844 here.

For engineers on AWS, it would be amazing to have a vectorized.io zipfile you could place on S3 with enterprise licence features stripped out built for Ubuntu 20.04 - and a cloud formation script similar to the one for AWS MSK so it is almost a drop-in replacement for testing/benchmarking. 

For testing it would also be amazing if you released a free https://github.com/localstack/localstack plugin to provide Red Panda mock AWS MSK on localhost. That is the easiest way for me to get Red Panda code into the Enterprise git repository.

**Comment by senior7515** [comment]
@chadbrewbaker we should have CloudFormation. that's a good point. we'll start there and see if there is adoption via this route. we already have docker+rpm+deb X {arm+x86} but the cloudformation is a good next step

**Comment by hcoyote** [comment]
@rkruze was there any initial work on this that we can refer to? 

If not, we could probably fire something up with terraform and convert the running build back to CF with something like [former](https://github.com/iann0036/former2)

**Comment by gene-redpanda** [comment]
Closing this as stale. We have a well supported alternative with terraform.
