### ISSUE TITLE
rpk config set fails because of list vs single issue

### ISSUE THREAD

**Issue by travisdowns** [redpanda-data/deployment-automation#48]
As described in https://github.com/vectorizedio/redpanda/issues/2958 things can go wrong when the _list_ syntax for some properties are mixed with the single map syntax.

This happens in the ansible deploy, where we use the single syntax, but it gets transformed to list and then subsequent redpanda configures fail to set that property because we can't overwrite a list with a single value.

The list format is preferred and supported by all tools, while the single value is effectively deprecated and not supported by some tools. We should use list syntax.

**Comment by r-vasquez** [comment]
With v22.2.1 now this shouldn't be a problem, need to test before closing.

**Comment by gene-redpanda** [comment]
Closed as stale
