### ISSUE TITLE
Latest version of rp has issues with redpanda-tuner starting from ansible

### ISSUE THREAD

**Issue by larsenpanda** [redpanda-data/deployment-automation#68]
First, I don't know why redpanda-tuner runs as a systemd service. 🤷‍♂️
Second and most importantly, redpanda-tuner now fails trying to run as a systemd service, at least when deployed with ansible. 
Rogger Vasquez saw it in action and is looking into it!

**Comment by WesWWagner** [comment]
Is this a verified issue? @r-vasquez  ?

**Comment by tmgstevens** [comment]
I've been seeing this on newer OSes, such as Fedora 37, RHEL9 and the latest Ubuntu. May be related, or may not be

**Comment by r-vasquez** [comment]
@tmgstevens Interesting, do you have a sample of the error? so I can check if it's something related to the clocksource tuner or something new
