### ISSUE TITLE
Add a playbook to install redpanda console

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/deployment-automation#73]
This needs a change in the terraform scripts as well.

An example of how the playbook would look like: https://redpandacommunity.slack.com/archives/C039U14NY04/p1662538501878789?thread_ts=1662124131.079259&cid=C039U14NY04

**Comment by tmgstevens** [comment]
This should be a role rather than playbook

**Comment by WesWWagner** [comment]
I will take ownership of this one.

**Comment by gene-redpanda** [comment]
duplicate issue
