### ISSUE TITLE
Improve EC2 instance naming

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/deployment-automation#76]
1. add `instance_name_prefix` variable and include at beginning of name tag
2. include `count.index` at end of name tag

**Comment by gene-redpanda** [comment]
This is implemented

<img width="356" alt="Screenshot 2023-04-21 at 12 11 49 PM" src="https://user-images.githubusercontent.com/123959009/233684718-a5fb4cf1-d63b-42d8-866c-cb7ab884652e.png">
<img width="496" alt="Screenshot 2023-04-21 at 12 14 59 PM" src="https://user-images.githubusercontent.com/123959009/233685159-3b05ac45-ceaf-46ce-bc1d-58e39c6e2b3c.png">
