### ISSUE TITLE
Switch to /public_metrics endpoint

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/deployment-automation#81]
The grafana dashboard is generated based off the internal `/metrics` endpoint. This should be switched to the public-facing `/public_metrics` endpoint.

https://github.com/redpanda-data/deployment-automation/blob/01d1c3fa8313a84ba5cb9a1f195161251889ac96/ansible/playbooks/deploy-prometheus-grafana.yml#L5

**Comment by hcoyote** [comment]
I was reading up on this. It looks like the public_metrics endpoint exists on 22.2+. Do we need to special-case this somehow to deal with ansible users sitting at a lower release version?

https://docs.redpanda.com/docs/manage/monitoring/

Also, is there anything more to do here than to update `--metrics-endpoint` to use the `/public_metrics` endpoint? Should it still use the private_ip for the host or should it work off a public_ip?

**Comment by hcoyote** [comment]
This should probably instead use the grafana dashboards we publish to the Grafana marketplace instead.

**Comment by hcoyote** [comment]
Alternatively, we should look at enabling releases on the observability project and pull bundled downloads directly from https://github.com/redpanda-data/observability

**Comment by gene-redpanda** [comment]
<img width="509" alt="Screenshot 2023-04-21 at 12 17 01 PM" src="https://user-images.githubusercontent.com/123959009/233685558-1af0a9bd-0120-48d8-82f4-126491fc232e.png">

This is done
