### ISSUE TITLE
Enable rack awareness

### ISSUE THREAD

**Issue by r-vasquez** [redpanda-data/deployment-automation#82]
The user should be able to opt-in for rack awareness with an ansible variable:  `-e enable-rack-awareness=true`

See: https://github.com/redpanda-data/deployment-automation/issues/65#issuecomment-1236692074

**Comment by vuldin** [comment]
Related issue: https://github.com/redpanda-data/redpanda/issues/6827

**Comment by WesWWagner** [comment]
Is this not complete via the support of the rack ids in hosts.ini ?

**Comment by WesWWagner** [comment]
This feature already exists in the current main line code base.

set rack=# in the hosts ini or extra vars , and rack awareness will be enabled and assigned to the correct rack ID.

**Comment by WesWWagner** [comment]
Already in /main as a feature
