### ISSUE TITLE
Revisit client configuration

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/deployment-automation#84]
- Terraform is configured to deploy a client EC2 instance (if `var.clients` is non-zero), but there is no ansible configuration to install the Redpanda CLI
- `var.clients` is an unbounded integer value, but maybe it should just be a boolean
- Wouldn't users still need to connect directly to nodes at some point (viewing logs, etc.)? Having a client seems like an added step, and we would need to explain to the user when to connect to the client and when to just connect to the node. Possibly a better route would be to remove the client.

**Comment by tmgstevens** [comment]
Sounds like with need a Redpanda client role that will configure /etc/redpanda/redpanda.yaml with the rpk values. Would need a bit of refactoring for the /etc/redpanda/redpanda.yaml template, but otherwise it's a reasonable request.
